---
- hosts: local
  become: true
  vars: 
    user: suporte
  tasks:
   - name: Adiciona a chave GPG para o repositório oficial do Docker
     ansible.builtin.apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present
     register: apt_key_add
   - name: Adiciona o repositório do Docker
     when: apt_key_add is succeeded
     ansible.builtin.apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
       state: present
     register: add_repo_docker
   - name: Instala o Docker
     when: add_repo_docker is succeeded
     ansible.builtin.apt:
       name: docker-ce
       state: present
       update_cache: true 
     register: install_docker
   - name:  Adicionando o usuário "{{ user }}" a grupo do Docker
     ansible.builtin.user:
       name: "{{ user }}"
       groups: docker
       append: yes
   - name: Reinicia e habilita o serviço do docker na inicialização
     when: install_docker is succeeded
     ansible.builtin.service:
       name: docker
       state: restarted
       enabled: yes
     
