---
- hosts: local
  vars:
    usuario: linus
    senha: $1$i5CwO/2J$JIaH55NqG10CDpYLqLAZf/
  tasks:
    - name: Adiciona usuário
      ansible.builtin.user:
        name: "{{ usuario }}"
        state: present
        shell: /bin/bash
        password: "{{ senha }}" 