---
- hosts: local
  tasks:
    - name: Instala o pacote NTP
      ansible.builtin.apt:
        name: ntp
        state: present
        update_cache: true
      register: ntp_installed  # Caso tenha sido instalado com sucesso registra o output de sucesso na variavel
    - name: Define o arquivo de configuracao do servidor NTP
      when: ntp_installed is succeeded  # Verifica se a instalação do ntp foi bem sucedida
      ansible.builtin.copy:
        src: /home/suporte/playbooks/ntp.conf
        dest: /etc/ntp.conf
        owner: root
        group: root
        mode: "0644"
